### ISSUE TITLE
can it be used to unity3D game？  someone tell me there are too many faces in the character

### ISSUE THREAD

**Issue by ironresolve** [animate1978/MB-Lab#103]
bad english   sorry

**Comment by telnetr4** [comment]
[Yes](https://github.com/animate1978/MB-Lab/wiki/Links#unity-related). Whether or not it works well is different question.

You were probably told that because the polycount of these characters are high. This creates a lot of detail but can cause lag on slower platforms. Removing the mbastlab_subdvision can drop the vertex count from around 138,000 polygons to around 34,000, [which is still high when compared to models found in other games](https://forum.beyond3d.com/threads/yes-but-how-many-polygons-an-artist-blog-entry-with-interesting-numbers.39321/). You may need to do some other polygon lowering stuff in order to make these models work well.

**Comment by ironresolve** [comment]
> [Yes](https://github.com/animate1978/MB-Lab/wiki/Links#unity-related). Whether or not it works well is different question.
> 
> You were probably told that because the polycount of these characters are high. This creates a lot of detail but can cause lag on slower platforms. Removing the mbastlab_subdvision can drop the vertex count from around 138,000 polygons to around 34,000, [which is still high when compared to models found in other games](https://forum.beyond3d.com/threads/yes-but-how-many-polygons-an-artist-blog-entry-with-interesting-numbers.39321/). You may need to do some other polygon lowering stuff in order to make these models work well.

understand       thankyou very much
