### ISSUE TITLE
JSON poses don't work as expected

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#11]
The weird thing for me is when I try to use the new versions of the jsons in Blender, if I load them manually, they work as expected, but if I put them in my downloaded copy of v1.65, they do not. I don't understand the code well enough to what I'm doing wrong.

_Originally posted by @blaisefaint in https://github.com/animate1978/MB-Lab/issues/3#issuecomment-448071974_

**Comment by blaisefaint** [comment]
I also uploaded adjustments I made to male poses:

https://drive.google.com/open?id=1iObEDgwKlWa7EpzR1zrvL5pjf5t4fScj

There are a lot more female poses than male poses currently in the lab.

Here's a playlist I made for the Manuel Bastioni Lab:

https://www.youtube.com/playlist?list=PL34ftZtLOIFAmyVsdCGa-uB6ab833GDQj

And here's a playlist I made using Make Human characters to animate the @2000 Carnegie Mellon bvh files:

https://www.youtube.com/playlist?list=PL34ftZtLOIFBG8Hwf91WVCoIsyOTkGOFK

Unfortunately, Make Human pretty much died when Manuel Bastioni left, and I was never able to get the CMU bvh files to work properly with the Manuel Bastioni Lab.

At this point, given the age of the CMU bvh files, I think it would be better to come up with new bvh files that are compatible with MB-Lab.

(I just don't currently have the resources to create them.)

It would also be nice to come up with a repository of open-source free as in beer base assets -- boots, shoes, slacks, t-shirts and so forth that just work with the lab. (They shouldn't necessarily come with the MB-Lab, because that can unnecessarily increase the file size.)

Does anyone know of any more up-to-date resources like this?

**Comment by animate1978** [comment]
You can just google drive it, as you have done for the json poses

**Comment by animate1978** [comment]
It's possible. I, for instance, get this weird screen flicker of past screens when I am finalizing the characters sometimes, like there is this screen buffer or something that keeps popping up and screws up my whole desktop for a few seconds. I am sure it is my issue because of my video card or something related to it, it is just strange it happens only when finalizing.

**Comment by animate1978** [comment]
Where do you have MB-Lab installed? The addon install is the same as the original ManuelBastioniLAB location.

**Comment by animate1978** [comment]
Ok. I am just wondering if you installed it directly into your addons folder or not. I am still trying to figure out why your having issues with poses.

Try uninstalling it, then download a new copy then install it again

**Comment by telnetr4** [comment]
In what way do "they work as expected"? Do they not show up or do the poses look warped?

**Comment by blaisefaint** [comment]
Where would the add-ons folder be?

**Comment by blaisefaint** [comment]
Okay, now it's working as expected. It looks like you committed the new jsons I created, is that correct?

Perhaps the difference is that when I tried before, I just overwrote the files in the poses folder, but the commit you performed was needed. I'm still new to Github and haven't tried to make any commits.

It might be helpful to provide instructions to people as far as proper installation.

I can't get images to load here. I've tried several times to post pngs, the smallest being 28.6 KB. Is there a file size limit, or should I try jpgs instead of pngs?

Here's a link to a tweet of the image: https://twitter.com/blaise_faint/status/1075263872058212352

**Comment by animate1978** [comment]
You can actually drag and drop images in comments :)

**Comment by blaisefaint** [comment]
I know, but when I try, I get an error message. It doesn't work as it should.

The message I get is "Something went really wrong, and we can't process that file. Try again."

Here's a link to the male captured. This doesn't look good: https://twitter.com/blaise_faint/status/1075265772652515328

**Comment by animate1978** [comment]
Yeah some of the geometry looks weird.

Ok since the original topic is no longer an bug, I am closing this issue.
