### ISSUE TITLE
Dislocated/disconnected bones and rolls not matching

### ISSUE THREAD

**Issue by danielenger** [animate1978/MB-Lab#137]
"MBLab_skeleton_muscle_fk" has these issues:
- "thigh_L/R" tail dislocated
- "calf_L/R" tail dislocated
- "foot_L/R", "toes_L/R", "clavicle_L/R" roll not matching with "MBLab_skeleton_base_fk"
- rolls of some fingers not matching with "MBLab_skeleton_base_fk"
- rolls of some arms and spine bones are slightly not matching with "MBLab_skeleton_base_fk"
- "toes_R" disconnected (has been fixed before in other armature)

"MBLab_skeleton_base_fk" and "MBLab_skeleton_base_ik":
- "toes_L" and "toes_R" roll not symmetrical

PS: I stumbled across the bugs while working on Rigify for MB-Lab add-on. The knees give me headaches.

**Comment by animate1978** [comment]
Currently working on these. Questions though.

When you say dislocated, what do you mean? I am confused that is all.

**Comment by animate1978** [comment]
Ok so when editing this rig, I have set the rolls of root, spines, neck and head to 0, saved the humanoid_library.blend file.... boot up another instance of Blender, create a new character and the rolls have not changed.

So this may take some time, I thought I had it but seems there is some problems

**Comment by animate1978** [comment]
>     * "thigh_L/R" tail dislocated
> 
>     * "calf_L/R" tail dislocated

* Still working on

>     * "foot_L/R", "toes_L/R", "clavicle_L/R" roll not matching with "MBLab_skeleton_base_fk"

* Fixed

>     * rolls of some fingers not matching with "MBLab_skeleton_base_fk"

* Fixed

>     * rolls of some arms and spine bones are slightly not matching with "MBLab_skeleton_base_fk"

* Fixed

>     * "toes_R" disconnected (has been fixed before in other armature)

* Fixed

> "MBLab_skeleton_base_fk" and "MBLab_skeleton_base_ik":
> 
>     * "toes_L" and "toes_R" roll not symmetrical

* Fixed, I think

**Comment by animate1978** [comment]
However I noticed some strange behavior of MB-Lab.

No matter what I do to the base armature in the base blend file, the rolls will slightly change when appended into the scene. So like the spines of the base skeleton and the muscles, they are set to 0.00 in the base file but then when appended by MB-Lab there will be a slight change of ~0.00010

This also happens to other bones as well.

There is also roll changes when editing the model in MB-Lab using the MB-Lab tools (Character Lib, random generator etc...), there will be roll changes even larger values there depending on how MB-Lab's algorithm changes the model and armature.

This was tested over the past 3 days, after replacing the rigs multiple times in the base file.

On a side note, it is very easy to replace / edit the armatures and the meshes in the library for future reference, the file is completely new and not based off of the file Manuel had written for 1.6.1. So that is a bonus research find.

**Comment by animate1978** [comment]
Has the issues been resolved? I am not %100 sure from my end.

**Comment by danielenger** [comment]
"thigh_L/R" tails are still dislocated in "MBLab_skeleton_muscle_fk".
Everything else looks fixed.

**Comment by animate1978** [comment]
I believe that with the new humanoid_library.blend file that was committed this morning this should be fixed

**Comment by animate1978** [comment]
Re-opened this up because I think it is still related to this bug...

https://github.com/animate1978/MB-Lab/issues/166
