### ISSUE TITLE
Principled Hair BSDF Shader attached to Hair

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#188]
**Is your feature request related to a problem? Please describe.**
When adding a new particle Hair, no shader is assigned.

**Describe the solution you'd like**
A basic Principled Hair BSDF node added to the Hair

**Describe alternatives you've considered**
This CAN be done by the user through the regular Blender interface, however it is a few extra clicks of the mouse that could be done via script.

![FINAL_TEST_particlehair](https://user-images.githubusercontent.com/479115/68400018-ee8b6600-013c-11ea-9a65-6efd4dc3b9bb.png)

**Comment by Noizirom** [comment]
That's going to take me some time. I've never programmed nodes. I'll put
that on the next update. I'm also going to find a way to add the shape
keys. I'm probably going to need a week or 2 to code and test.

**Comment by animate1978** [comment]
No rush, just an idea at the moment

**Comment by animate1978** [comment]
As reminded on Discord - Principled Hair BSDF only works in Cycles.

https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/hair_principled.html

**Comment by Noizirom** [comment]
I'm trying to make a preset for EEVEE. I'm making some headway with the
hair cards. Tested in CYCLES and EEVEE. Somewhere down the line I want to
find a way to get the particle hair to set the hair color for the hair
cards when converting. I also eventually want to add the ability to draw
hair cards with the grease pencil.

**Comment by econundrum** [comment]
Can I also suggest setting the hair root width down to 0.01 or 0.02 the default is way to thick for human hair.

**Comment by Noizirom** [comment]
I will take a look at it.  It will be a part of the next update. 


Powered by Cricket Wireless
-------- Original message --------From: econundrum <notifications@github.com> Date: 11/17/19  4:36 PM  (GMT-05:00) To: animate1978/MB-Lab <MB-Lab@noreply.github.com> Cc: Noizirom <noizirom@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [animate1978/MB-Lab] Principled Hair BSDF Shader attached to Hair (#188) 
Can I also suggest setting the hair root width down to 0.01 or 0.02 the default is way to thick for human hair.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/animate1978/MB-Lab/issues/188?email_source=notifications\u0026email_token=AKYHC3V6TAUIWZ6MEUZAI3DQUG2OXA5CNFSM4JKH7BH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEIWY7Y#issuecomment-554790015",
"url": "https://github.com/animate1978/MB-Lab/issues/188?email_source=notifications\u0026email_token=AKYHC3V6TAUIWZ6MEUZAI3DQUG2OXA5CNFSM4JKH7BH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEIWY7Y#issuecomment-554790015",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by animate1978** [comment]
I think this can be closed now
