### ISSUE TITLE
How to help with the translation? Как помочь с переводом?

### ISSUE THREAD

**Issue by SergeyRom-23** [animate1978/MB-Lab#207]
Hello. With the English language is not always clear. Therefore, I translated a little into Russian. How and where should I send a translation to add it to the addon?

Всем привет. С английским языком не всегда понятно. Поэтому перевёл немного на русский язык. Как и куда мне отправить перевод, что бы его добавили в аддон ?

**Comment by Noizirom** [comment]
I’m not really sure, but you could try putting it in a fork. Sent from Mail for Windows 10 From: SergeyRom-23Sent: Monday, December 2, 2019 11:54 AMTo: animate1978/MB-LabCc: SubscribedSubject: [animate1978/MB-Lab] How to help with the translation? Как помочь с переводом? (#207) Hello. With the English language is not always clear. Therefore, I translated a little into Russian. How and where should I send a translation to add it to the addon?Всем привет. С английским языком не всегда понятно. Поэтому перевёл немного на русский язык. Как и куда мне отправить перевод, что бы его добавили в аддон ?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by animate1978** [comment]
There is a fork for another language here if you want to take a look...

https://github.com/millionart/MB-Lab_zh-Hans

**Comment by Noizirom** [comment]
Thank you.

**Comment by SergeyRom-23** [comment]
Good time. Thanks for the link, it’s convenient to watch how this is done. Soon I will make a branch in Russian on github.
But the question remains and becomes more precise: when I create a character, "CREATION OPTIONS"->"Create character"->"CREATION TOOLS"->"Bodu Measures"->"Measurements"-> /Abdomen/Arms/Body and other morphing categories remain in English. How can I change them?

Доброе время. Спасибо за ссылку, удобно смотреть как это делается. В скором времени сделаю ветку на Русском языке на github. 
Но вопрос остается и становится более точным: когда я создаю персонаж, 
"CREATION OPTIONS"->"Create character"->"CREATION TOOLS"->"Bodu Measures"->"Measurements"-> /Abdomen/Arms/Body и другие категории морфинга остаются на английском языке. Как мне их изменить?
![Снимок экрана_2019-12-10_09-27-57](https://user-images.githubusercontent.com/58438338/70501585-7e9f3f80-1b2f-11ea-8adf-c5515d69aef0.png)

**Comment by Noizirom** [comment]
I'm not 100 percent sure,  but I think you may have to change the .json
files in the "data" folder. There is a "morphs" folder and several others
inside.

**Comment by animate1978** [comment]
Unfortunately I am closing this issue because there does not seem to be a clean solution for translation of languages other than modifying the source per language....
