### ISSUE TITLE
Commercial usage of characters created with MBlab

### ISSUE THREAD

**Issue by TheBricktop** [animate1978/MB-Lab#215]
Is it possible to create a commercial product using mb-lab meshes? 
If AGPL license is viral, why not change to lgpl or mit, if only for meshes not the code.

**Comment by mysticfall** [comment]
I also happened to notice this just today. I've been using the original MBLab for a while in a game project and I knew that the models are covered by AGPL by default.

But if I'm not mistaken, they were dual-licensed with CC-By, so I hadn't thought much of it when I switched to this fork but today I happened to notice that now it's just AGPL, which would make using the models in a non-GPL game project almost impossible.

Is there any reason why the project does not offer CC-By license for generated models anymore?

**Comment by animate1978** [comment]
If you used ManuelBastioniLAB 1.6.1 that was unmodified then yes the dual license still applies. What happened is that as soon as I started editing the addon this in effect broke that dual license and legally had to go AGPL3. There is not much I can do about it and it has caused a lot of frustration, which I can understand. 

The way Manuel had licensed the models, the JSON library and images kind of makes it impossible at this time to change anything legally until we can replace the models and the subsequent files associated with the project, a monumental task.

I wish at this time I could say we are on our way to doing that but it is not that case, we are about 1/8 the way to change anything with base meshes and the files associated and because we kind of hit a brick wall it is unknown when / if this will happen.

I am very sorry

**Comment by mysticfall** [comment]
Thanks for the explanation. I suppose I should just relicense my own project under AGPL now as it will allow me to freely use all the morph data which I've avoided so far :)

But I found it a bit surprising since I've never thought a forked project with dual licensed terms would work that way.

Could you refer me to the part of the license which mandates such a restriction, namely that you'd lose the dual licensing option if you modify any part of the codebase?

I'm not complaining because I fully understand that it's a matter you can't really change. But I'd like to understand the situation better, as this is the first of such a case I've encountered where forking a project and modifying it under the same license would have such an implication, so I feel rather curious.

**Comment by Noizirom** [comment]
I'm not sure if this applies,  but I came across this. Hope it helps.
https://softwareengineering.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application/47048#47048

**Comment by mysticfall** [comment]
@Noizirom // Thanks for the info. I think I'm already familiar with most of what was explained in that comment. But would it also apply to the original author's provision that contents generated with his software can be used with a different license than AGPL?

It's undoubtedly true that any modification to the original codebase must be subject to the terms of AGPL/GPL. But normally a software license does not automatically apply to contents created by that software. The only reason, as I understand it, which makes such contents to be subject to AGPL is the fact that it's based on AGPL base materials (e.g. base mesh).

The closest case I can think of is GNU Classpath project, which is a clean room implementation of Java Virtual Machine. It's licensed under GPL, but to prevent Java programs running on top of it to be subject to the same license terms (because it dynamically link to the core API which is GPL), they added an exceptional clause to explicitly allow such a usage.

In both of the cases, the software is a tool by which users can create their own contents, and the owner of the codebase wanted to allow the users freely creating non-GPL contents with their software.

And I don't think I'd lose the exception clause if I fork GNU Classpath and make a few changes, so I believe there's a chance that the same logic could apply to a forked version of MBLab, when it is clear the original author's intention was to allow using his tool to create non-GPL contents.

Of course, the definite answer can only be given by Manuel Bastioni himself. But if what I said above is reasonable, maybe we could try to contact him and ask for a clarification on the matter.

**Comment by Noizirom** [comment]
Several of us have tried to reach out to him in the past.  We were
unsuccessful.

**Comment by animate1978** [comment]
https://github.com/animate1978/MB-Lab/wiki/Asset-Licensing/128d8d527ee458fdec13d285dbd71cf3c31d88de

This was the FAQ taken from Manuel Bastioni's website before he shut down, I duplicated it here but then modified the page a couple weeks ago because people were getting confused about the whole deal. The URL is a revision history from June 9.

**Comment by mysticfall** [comment]
I think article 1.12 removes any doubt about this issue now. I didn't remember there was such a clause because at that time I read it, there was no forked versions so I probably didn't take notice.

Thanks for the clarification!

**Comment by TheBricktop** [comment]
It's such a shame that Manuel had given up on the community so hard.

**Comment by RustoMCSpit** [comment]
is there any update on this?

**Comment by RustoMCSpit** [comment]
> It's such a shame that Manuel had given up on the community so hard.

is there any way to contact him now?

**Comment by RustoMCSpit** [comment]
> But would it also apply to the original author's provision that contents generated with his software can be used with a different license than AGPL?
It's undoubtedly true that any modification to the original codebase must be subject to the terms of AGPL/GPL. But normally a software license does not automatically apply to contents created by that software. The only reason, as I understand it, which makes such contents to be subject to AGPL is the fact that it's based on AGPL base materials (e.g. base mesh).

maybe a loophole can be found here where instead of importing a model, mb-lab uses math to generate the model in the exact same way initially, technically that would be a content created, and not something that came with it, and thus not be subject to the license
