### ISSUE TITLE
How to modify base meshes?

### ISSUE THREAD

**Issue by mysticfall** [animate1978/MB-Lab#216]
I'm using MBLab for a game project and I often encounter such cases where I need to modify the generated characters here and there, like changing UV mappings, add more details to some body parts, and so on.

However, it becomes quite a daunting task once the number of generated characters grows large, so I wonder if there can be anyway if I can make such changes to `humanoid_library.blend` itself, so I can just regenerate all derived characters from saved JSON files instead.

Is it something possible? If so, where I can learn about the process?

I don't mind if it'd be a complex task since it'd still be much better than having to manually apply such changes for every character.

Thanks in advance!

**Comment by lebrewer** [comment]
I also need to do the same thing, mostly to arms and hands. 👍

**Comment by animate1978** [comment]
This is a subject that us developers are also having issues with because we don't have the tools that Manuel had at his disposal, we are thinking he used custom scripts that are not publicly available.

The JSON and the code, as well as the humanoid_library blend file are very tightly interlinked together. If you alter something without thinking it through, it WILL break the addon, such as adding polygons or vertices as these are "recorded" in JSON, and it's library of morphs. So if you modify the mesh, it will not show up as normal in Blender, you will get an error.

One of the devs, @Noizirom , has managed to write some scripts to export SOME of the required information to introduce new bash meshes, or edit them but they are basic and only export vertex, polygon and vertex groups out to JSON. There still needs the morph library for the meshes (to make them young, old, skinny fat and in between), the expressions JSON as well as several other smaller and less known about JSON files. These tools are available here -

https://github.com/animate1978/MBLAB_DevTools

Then there is the weight painting which is vital to the whole thing as well, if not done correctly you get this - 
https://vimeo.com/359182294

There is also the requirement to edit the character_config.json file as well, if the vertex count doesn't match, MB-Lab will error out.

For UV editing however it is pretty easy if you know what you are doing, we've done some minor UV edits to MB-Lab already.

But mesh editing is not possible at this time, as in adding or deleting vertices, polygons and so on.

**Comment by mysticfall** [comment]
Yeah, that video looks familiar :sweat_smile: I've already tried editing the library and got something similar to that... er... interesting result.

At least, I'm glad to learn that editing UV is possible. I wanted to modify the UV map for eyelashes, so they wouldn't be so all over the place.

Thanks for the detailed explanation. I wish we could find a way to customize the base mesh eventually.
