### ISSUE TITLE
Question / Request : Resources related to aging

### ISSUE THREAD

**Issue by Illasera** [animate1978/MB-Lab#220]
As far as i know, When generating a character with : "MB-Lab",

Age depended, Multiple facial and bodily factors are influenced in their size, shape and volume.
I am aware that MB-Lab's goal is towards realism, proportions wise.

I would like to know for my own modeling practices, From what resources / studies / journals,
MB-labs pull information as to the changes in proportions of the body with respect to age factor.
Requesting link to studies related to : (What parts are affected by aging and in what way) that MB-labs basing its own model generation on.

*I know MB-labs back then released a graph detailing changes, but i want to cross reference with the studies its relying on.

**Comment by animate1978** [comment]
I have no idea where Manuel had gotten his information, so there is speculation if any of it is actually accurate.

The age / mass / tone are just a simple algorithm ( for math nerds I guess ) that can be found here - 

https://github.com/animate1978/MB-Lab/blob/e3a0c1fc579a4acd3fa86c433aa3bc634ba5fe94/__init__.py#L2278

But as for what it's based on is anyone's guess at this point.

**Comment by Illasera** [comment]
I understand, A bit worrying (That we are going for blind trust) but can't be helped.

If there was a way to get in touch with "Manuel " would be helpful but either way.

Thanks anyway.

**Comment by animate1978** [comment]
Unfortunately when Manuel had stopped developing ManuelBastioniLAB he also stopped responding to any social media and email as well, he pretty much dropped off the internet and has not been heard from since. He even shut down his website so any docs related to his project are lost as well.

This is how MB-Lab came into being, just took the last code and files he released (version 1.6.1) and then put it up here, it has evolved since.
