### ISSUE TITLE
missing file humanoid_library.blend

### ISSUE THREAD

**Issue by JackOfShadow** [animate1978/MB-Lab#239]
version 1.6.5 and 1.6.5b - MB-lab\data\humanoid_library.blend not found. And there are no textures

**Comment by animate1978** [comment]
Ah yes. This would eventually come up. So what happened is that the repo size got too big from the commits of the large binary files and I had to do some surgery to clean it out, this effectively wiped all the actual binary files from the commit history - which includes the blend file and textures.

This goes all the way back too so any commits I made or releases since the initial commit are wiped.

BUT this is not a problem because I have all versions backed up and am transferring them to my website here - www.mblab.dev

The 1.6.5 version is uploaded now. I am just prepping it for public viewing and it should be ok to go.

**Comment by JackOfShadow** [comment]
Thank you!
