### ISSUE TITLE
Current Goal?

### ISSUE THREAD

**Issue by telnetr4** [animate1978/MB-Lab#3]
Im not sure how to ask this, but what are the current goals for this project?

I personally would like to suggest working on some ease of use modifications.

**Comment by animate1978** [comment]
The current goal for this MB-Lab would be to try to incorporate better texture maps, I have already modified the shaders a little to try to achieve better realism.
As for ease of use modifications, I would love to try but not sure where to begin, my coding skills are limited but I have been reviewing the code quite a bit trying to make sense of it.

Personally I want to get the addon to 1.7.0 as Manuel was trying to do before we tackle the Blender 2.80 update.

**Comment by telnetr4** [comment]
Textures is not an area of expertise for me, but from what I can see about you I don't think that's going to be a problem.

I'm still getting familiar with the code, but when I get a chance I'll see if I can make some modifications to at least the UI.

**Comment by slepyhed** [comment]
I have spent a considerable amount of time studying MBLab's code. I'm certainly willing to help out - I'd love to take a stab at getting this to work in 2.8.

However, I don't think its worthwhile unless we can get the licensing worked out. Once I figured out what was allowed under the licence, I stopped working on modifying code because it just seemed like a dead end.

**Comment by fornof** [comment]
I have a few questions:
1. what is the licensing currently? 
2. Would issue tracking be better supported on Gitlab or Phabricator? 
3. I see this could be ported to 2.8 , and textures redone. are there any other issues ?

**Comment by blaisefaint** [comment]
Many of the default poses for MB-Lab are wrong. For example, in captured01 the arms pass through each other.  In addition, many of the poses are optimized for nude, hairless characters and cause conflicts when you add clothes or hair.

I'm attempting to correct some of these poses. 
https://twitter.com/blaise_faint/status/1074674994234486784
What is an appropriate way to submit them for consideration here?

The #mblab hashtag is taken on Twitter. What hashtag should  people use to refer to this project on Twitter?

**Comment by BradWBeer** [comment]
Hello. I'm a gamedev who is using MB-Lab for my characters. I don't know if this is correct place to ask, but is there a discord or IRC server we can use to discuss MB-Lab? I don't want to clutter the project with spurious issues. 

Also, my major requirements are a solid rig. Right now I use Auto-Rig Pro. It works well...but I have issues with weight painting at times. I also need Auto-Rig Pro to create a nice skeleton to export for Unreal Engine. (The current MBLab characters are very small, btw.) Also, I could use some action poses and animations. (I'm willing to share anything I create.) Walking, running, aiming, etc. would be hugely beneficial for me. 

I would also like a way to choose how many polys my character will use...or better yet, to create several LOD meshes. Then again, I'm just shouting out a wish list. 

Can we set up a discord for this type of conversation? Otherwise finding a common direction will be unbearably slow.

**Comment by blaisefaint** [comment]
I'm not familiar with discord and haven't used IRC in over a decade. My vote would be for Twitter.

**Comment by BradWBeer** [comment]
Twitter is more for announcements. It has a hard limit on length and doesn't have multiple channels. Also...there are political concerns with twitter these days. I know people who avoid it for that reason.

**Comment by NumesSanguis** [comment]
I agree with Twitter more being a tool for announcements. I like IRC, but I think it's getting out of favour. Therefore, I guess the go to tools for discussion would be either [Discord ](https://discordapp.com/ )or [Slack](https://slack.com/). Here is a comparison of the two: https://www.chanty.com/blog/discord-vs-slack/

Slack has more a focus on work, but since MBLAB characters are often used for games, users of this add-on might already be active on Discord. User-base is important. Discord is stronger on the voice/video part, but on the other side we might prefer to keep discussion in text form, so every member will have access to the same information.
Slack is maybe easier to hook-up with bots? In case we want automatic announcements of new versions?

I use both, so for me it doesn't matter. Experience with both of them have been good to me.

**Comment by BradWBeer** [comment]
Blender, Unreal Engine and several of their related tools officially use discord. We can piggyback on blender's until we figure out what we want. How about #blenderpython?

**Comment by macronomicus** [comment]
There seems to be more flexibility in the license than some are thinking?

He says on the License page.
**Alternatively, for closed source games or closed source 3D models, it's possible to choose, for characters generated by the official[*] software, the Attribution 4.0 International, giving to Manuel Bastioni the credit as required by that license:** 

So theres a way to give attribution and respect back to him, that seems fair to me and a nice thing to do in most situations where theres little customization, but if you invest massive time creating a very unique thing I think  maybe requiring attribution may seem a bit much to some folks in that situation.

Seems he also stipulates a difference between the official software downloaded at his website or from elsewhere.  Any added flexibility comes from that being that this is a fork?

This is why companies have a team, each person has strengths and the should run with them, you cannot expect a software dev with such passion as Manuel to be also a marketing expert lol, its completely different and extremely complex knowledge and skillset for each area!  Im amazed he made it as far as he did all alone, no developer should be left alone all the time, they need support and a team.

**Comment by animate1978** [comment]
> I've posted a zip file of 22 adjusted poses here: https://drive.google.com/open?id=1ph_xTnf4TC9ixCfQQaKSmBpTkDZYIbGD
> 
I have downloaded these and have put them into the respective directory and will commit them sometime soon

**Comment by blaisefaint** [comment]
The weird thing for me is when I try to use the new versions of the jsons in Blender, if I load them manually, they work as expected, but if I put them in my downloaded copy of v1.65, they do not. 

I don't understand the code well enough to what I'm doing wrong.

**Comment by animate1978** [comment]
https://github.com/animate1978/MB-Lab/wiki/Asset-Licensing

**Comment by animate1978** [comment]
Think this can be closed now
