### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#58]
So I looked into getting a site, forgetting that pretty much ALL hosts charge yearly, despite putting monthly prices on display. Long story short, cannot afford to buy hosting space and domain at this time. So looked into the Github site pages thing, set up an organization, made a new repo for this site and have a new "test" site at this time. It is NOT production ready so to speak, I used a template I found off the web so it still has it's default pages and images but I edited it enough to convey the idea.

https://mb-lab-community.github.io/MB-Lab.github.io/index.html

I am working on some imagery right now so I can replace said images, I think I like the look and feel I just need to add more.

Yes? No?

**Comment by telnetr4** [comment]
Can we use assets from the Manuel Bastioni site?

**Comment by telnetr4** [comment]
> Why don't you try Wix? That's the site I use and it's free. I haven't had a chance to see your site yet but I'll let you know

Have you ever used Wix in a collaborative setting? Is there a way to see exactly who changed what and when and allow for easy reverting of changes? Is there an in-system way for others to suggest changes? I've barely used Wix, but I know that Github pages can do all this and more. The main problem with it is it isn't as WYSIWYG like Wix out of the box; you have to find your own coding solutions.

> I also got a complete archive of the website but he did put copyrights for the site, so I am not using the HTML. Some images also have copyrights but a lot of the imagery does not and some are CC-BY-ND I believe, it's those I want to incorporate.

I should probably take my archive off Github in that case. As you said, imagery are what was mostly important from that site.

**Comment by animate1978** [comment]
I found Wix very laggy on my system, could just be my system of course. I do have a portfolio there as well but barely use it anymore.

Eventually the idea is to have an actual site, but I can't afford to plop down $115 in one go, at least not right now, thus this "test" site, that may or may not be the actual site. The only problem between this site being hosted here is the URL is kinda long. Not memorable, so bookmarks are a necessity for people to come back to it. That's pretty much my only gripe about it being hosted here. Otherwise I think for collaborating with others on getting some serious docs on how to use MB-Lab this is perfect.

**Comment by telnetr4** [comment]
I'm pretty sure Github.io can host a website on a custom domain. Actually getting a non-sniped domain costs at most tens of dollars.

**Comment by SleeperG** [comment]
Hello. First I'd like to say thank you for your hard work at keeping this awesome add-on alive. I have a question that's unrelated to your site but I don't know how else to ask you questions. Manuel was improving the topology of the base meshes for his now cancelled 1.7 release. I'd like to do that to my base meshes in the origin Blender file but would also like to keep the shape keys and other Lab features. After I improved the meshes where in the code would I need to make changes and what would those changes be? I know that one would be very and bone location but after that I'm stumped. Thanks

**Comment by telnetr4** [comment]
> Hello. First I'd like to say thank you for your hard work at keeping this awesome add-on alive. I have a question that's unrelated to your site but I don't know how else to ask you questions. Manuel was improving the topology of the base meshes for his now cancelled 1.7 release. I'd like to do that to my base meshes in the origin Blender file but would also like to keep the shape keys and other Lab features. After I improved the meshes where in the code would I need to make changes and what would those changes be? I know that one would be very and bone location but after that I'm stumped. Thanks

I suggest making a separate issue as a question (press new issue and then the button to ask a question).

**Comment by SleeperG** [comment]
Thanks.

**Comment by harmoniser** [comment]
I am so happy to see that you are keeping this project alive. It's kind of sad what happened, and I guess it was a surprise to all of us. Manuel is certainly a creative genius, but sometimes such people are not as good with the money making part. 

I think a very nice thing to do would be to set up that web site, with some donation system, Patreon or whatever, then let the profits go to Manuel. He deserves it. 

I have a web server which could be used for the web site if you want, until there is enough income to pay for hosting.

**Comment by animate1978** [comment]
I honestly would love to set up some kind of patreon site or some other donation system to help Manuel out, as you said he deserves it after spending the past nearly 2 decades working on digital humans, however I just have no clue how to contact him as he has shut down all his social media accounts. IF contact could be established then maybe it will be considered and set up.

I just feel weird accepting donations for something I didn't build from scratch, that's all.

As for the web server space, I will think about that. Will have to get back to you on that :)

**Comment by gllms** [comment]
If the long domain name is the only problem here, you could also register a free .tk domain name at [freenom.com](https://my.freenom.com/domains.php) and forward it to the github site. The maximum time period is one year, but you could just register it again every year.
mb-lab.tk doesn't look too bad.

**Comment by grapemix** [comment]
I am totally down for a Patreon page. I will register and donate just because of you guys. After Manuel declared the dead of this project, it was first time we knew Manuel actually need helps more than just liking and sharing his youtube videos. I understand Manuel is upset because he thinks his work is not being cherish by the others, but that is not true. Lots of us would like to help, but we just don't know where to start.

For example, @animate1978  mentioned he had a hard time to reverse engineering the JSON data once. I also experienced the same problem too when I played around the code. It will be time consuming to contribute to a codebase without doc, clean test case and examples. In general, the code is realively clean, but we still need some ways to allow new developers to contribute. Moving the code to github/gitlab is a good start. May be we can create issues and use the "need help" label to distribute features and recruiting developers by features? 

We need a community to support our developers and new users. I am glad the discord channel and get a thread in blender nation were created, it might be hard to search old topics though. If we the cost of forum is a problem, may be we can consider [discource](https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/) or something similar.

If Patreon is a problem because of multiple contributors, may be we can raise money by feature. Something like beerpay or whatever similar might help. Developers get donation by which features they have contributed to. Of course, we should have a generic donation pool for main contributors involved/guided in multiple features.

Finally, thanks all for building this plugin, especially Manuel and @animate1978

**Comment by animate1978** [comment]
I've been looking into it recently, a Patreon page. Maybe with daily dev updates or something, I am not sure just yet exactly what to showcase there. BUT the thought is there.

**Comment by animate1978** [comment]
So I caved to pressure I guess and am rolling out a Patreon account here - https://www.patreon.com/mblab_development

It will feature blog style behind the scene work that isn't really seen by the public, I have folders stuffed with WIP renders and screenshots that never see the light of day, mostly for review by myself.

It's an idea at least. I don't know...
