### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#79]
Been busy working on documentation for MB-Lab, so far it has been a learning experience being that I never used Sphinx before.

It is very much a WIP but you can see the progress so far here : 

https://mb-lab.readthedocs.io/en/development/index.html

**Comment by blaisefaint** [comment]
FPC-Virtual has been making YouTube videos discussing MB-Lab:
https://www.youtube.com/watch?v=JTicudol9Dk
https://www.youtube.com/watch?v=2fN634AsvEo

I am somewhat confused, because apparently 1.71 is not yet available via Github, but is available via this page: https://blenderartists.org/t/mb-lab-1-7-1-release-for-blender-2-80/1138777/85

However, apparently the version of 1.71 demonstrated in the video is different from the version of 1.71 currently available now.

It looks like at one point you included clothing assets, but then you removed them and added them to a separate zip file (also available via https://github.com/animate1978/MB-Lab-DemoAssets), so people watching these videos might be confused. It might be good to post in the comments for FPC-Virtual clarifying this point. To get these assets to work, I had to append them and go into each individual blend file for them.

What I've read of the documentation looks good, and I'm looking forward to more on the clothing and hair. For example, the hair assets that come with MB-Lab 1.71 are actually saved in blend files in the assets subfolder of data, yet when I try to add assets for the clothes by clicking on the blend files in the unzipped folder of the demo assets, that does not work for me. What is the correct format for an asset to be loaded via the assets library?

**Comment by animate1978** [comment]
Yeah I completely overlooked the fact that there was no release for 1.7.1, mainly because it had a lot of bugs that I wanted to work out, so in the midst of that I never released it on GitHub. Now that it is stable again I think I should, probably tomorrow morning.

I did include the assets but caught some flak from it because the file size was so big, for me it was not a big deal I am used to downloading large files but in the end opted to remove them and just keep it focused to the addon. That does get me thinking though is to at least add shirt and pants, shoes as a basic demo for future releases? I guess that is what we tried to do here but it was too much I think, if it was trimmed down to a basic set to showcase what the proxy fitting does then it might get a better reception.

As for your last question that sounds like something I need to test.

**Comment by NumesSanguis** [comment]
Is it possible to have in Blender in our add-on tab a Download button for basic clothes?

**Comment by telnetr4** [comment]
> Is it possible to have in Blender in our add-on tab a Download button for basic clothes?
I think it is possible by using the requests library.

**Comment by animate1978** [comment]
OK so now after a week or so of doing this I think it is ready to be merged from Development to master, it still needs work but the majority of it is there.

https://mb-lab.readthedocs.io/en/development/index.html

**Comment by blaisefaint** [comment]
This is fantastic!

You've done a great job helping end users to understand this complex tool.

Thank you very much.

**Comment by animate1978** [comment]
Documentation link has been added to wiki, think I can close this.
