### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by DemonRem** [animate1978/MB-Lab#94]
why does the MB-Lab not appeared on the blender 2.80 the blender detect and installed the plugin but I can't even find it , I use the latest version of the plugin and I also try it on blender 2.79b but on the 79 it's cannot be install

**Comment by echoalien1985** [comment]
为什么没有人回答？我也想知道它

**Comment by DemonRem** [comment]
english

**Comment by animate1978** [comment]
Have you checked out this page on the wiki?

https://github.com/animate1978/MB-Lab/wiki/Installation

There could be periods in the zip file you are downloading. You may need to rename the zip file and the folder inside to MB-Lab-1-7-2 instead of MB-Lab-1.7.2. Blender does not like periods in zip file addons.

**Comment by telnetr4** [comment]
Can you give us some more information? What version did you try installing? What did you 

Does Blender spit out any errors when you open the system console? (Window>Toggle System Console)

Lastly, in 2.80 the window starts hidden. Click the < to the left of the XYZ view controller to open the right-side panel, then click the MB-Lab tab. This will only show up if you are set to the Layout Workspace.

If you are able to figure it out, let us know. If not, give us more information like details about how you installed it.

**Comment by echoalien1985** [comment]
![image](https://user-images.githubusercontent.com/47836981/53170182-7286d780-361a-11e9-8c2f-7c01b2c92d74.png)
this is here ,download...,is right

**Comment by DemonRem** [comment]
Once I back I try that and I will report

**Comment by DemonRem** [comment]
![1](https://user-images.githubusercontent.com/29927382/53187940-e1f5ca80-360c-11e9-817f-7a719cdb685d.png)

I using windows 10 64 bit
blender 2.8 beta

**Comment by telnetr4** [comment]
@echoalien1985 
Ok. That link will only work for Blender 2.80. If you want to use Blender 2.79 use [1.6.5](https://github.com/animate1978/MB-Lab/releases/tag/1.6.5b) or the [experimental backport](https://github.com/telnetr4/MB-Lab/releases/tag/1.7.2Backport).

@DemonRem 
Next time copy and paste what's in the terminal instead of taking a screenshot. For best results, select all before copying (you have to use keyboard shortcuts; click on the console, CTRL-A then CTRL-C)

I'm not sure what's causing this problem. I'll try to look into this further. The only thing I can think of doing in the meantime is to check the addon folder to make sure you've deleted any old versions of MB-Lab; the main user addon folder is in %appdata%\Blender Foundation\Blender\2.80\scripts\addons then make sure MB-Lab is checkbox is enabled in the preferences panel.

**Comment by DemonRem** [comment]
i did you action and the terminal show me that after reinstalling the module : 
`Modules Installed (MB-Lab-master) from 'C:\\Users\\AlisiaChan\\Downloads\\MB-Lab-master.zip' into 'C:\\Users\\AlisiaChan\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'`

where can i find the module then?

**Comment by telnetr4** [comment]
That means you installed it. Now activate it by checking the box. It should look like this (the name might be slightly different):

![capture4_li](https://user-images.githubusercontent.com/21324243/53212722-2754d080-35ea-11e9-94fa-c152fe822700.jpg)

**Comment by DemonRem** [comment]
I did it

**Comment by animate1978** [comment]
> 
> Something to note is that in 2.80 the window starts hidden. Click the < to the left of the XYZ view controller to open the right-side panel, then click the MB-Lab tab. This will only show up if you are set to the Layout Workspace.
> ![capturecirc3](https://user-images.githubusercontent.com/21324243/53159843-c4702480-356a-11e9-8d70-e056e39026d8.PNG)
> 
> If you are able to fix it, let us know. If not, give us more information like details about how you installed it.

If it installed simply press "n" while in the Layout workspace or click the < as described above

**Comment by telnetr4** [comment]
If you don't see it in the Blender Preferences window, that could mean several things.

Go to your addons folder (%appdata%/Blender Foundation/Blender/2.80/scripts/addons). There should be a MB-Lab folder there. If there's any periods (.) in the name, remove them.

If there isn't any MB-Lab folder, extract the .zip file into this addons folder then check preferences again. Again make sure there isn't any periods in the folder name.

**Comment by DemonRem** [comment]
@telnetr4 
Solved thank a lot
